name: My first workflow
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: windows-latest
    steps:
      - name: Print Hi
        run: |
            echo "First output"
            echo "Second output"
